// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Football API
//
//  This is a simple Football API
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /football-api/1.0.0
//  Version: 1.0.0
//  Contact: <justym8132@gmail.com>
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
