// Code generated by go-swagger; DO NOT EDIT.

package teams

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/justym/football-api/api/models"
)

// FindTeamsOKCode is the HTTP code returned for type FindTeamsOK
const FindTeamsOKCode int = 200

/*FindTeamsOK success finding teams in the seasons

swagger:response findTeamsOK
*/
type FindTeamsOK struct {

	/*
	  In: Body
	*/
	Payload *models.SeasonTeams `json:"body,omitempty"`
}

// NewFindTeamsOK creates FindTeamsOK with default headers values
func NewFindTeamsOK() *FindTeamsOK {

	return &FindTeamsOK{}
}

// WithPayload adds the payload to the find teams o k response
func (o *FindTeamsOK) WithPayload(payload *models.SeasonTeams) *FindTeamsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find teams o k response
func (o *FindTeamsOK) SetPayload(payload *models.SeasonTeams) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindTeamsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// FindTeamsBadRequestCode is the HTTP code returned for type FindTeamsBadRequest
const FindTeamsBadRequestCode int = 400

/*FindTeamsBadRequest bad request

swagger:response findTeamsBadRequest
*/
type FindTeamsBadRequest struct {
}

// NewFindTeamsBadRequest creates FindTeamsBadRequest with default headers values
func NewFindTeamsBadRequest() *FindTeamsBadRequest {

	return &FindTeamsBadRequest{}
}

// WriteResponse to the client
func (o *FindTeamsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
