// Code generated by go-swagger; DO NOT EDIT.

package teams

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// FindTeamsHandlerFunc turns a function with the right signature into a find teams handler
type FindTeamsHandlerFunc func(FindTeamsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn FindTeamsHandlerFunc) Handle(params FindTeamsParams) middleware.Responder {
	return fn(params)
}

// FindTeamsHandler interface for that can handle valid find teams params
type FindTeamsHandler interface {
	Handle(FindTeamsParams) middleware.Responder
}

// NewFindTeams creates a new http.Handler for the find teams operation
func NewFindTeams(ctx *middleware.Context, handler FindTeamsHandler) *FindTeams {
	return &FindTeams{Context: ctx, Handler: handler}
}

/*FindTeams swagger:route GET /teams/{seasonCode} teams findTeams

Teams when the season

Teams when {seasonCode}


*/
type FindTeams struct {
	Context *middleware.Context
	Handler FindTeamsHandler
}

func (o *FindTeams) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewFindTeamsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
