// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
)

// Score score
//
// swagger:model Score
type Score int64

// Validate validates this score
func (m Score) Validate(formats strfmt.Registry) error {
	return nil
}
