// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SeasonRounds season rounds
//
// swagger:model SeasonRounds
type SeasonRounds struct {

	// name
	// Required: true
	Name SeasonName `json:"name"`

	// rounds
	// Required: true
	Rounds []*Round `json:"rounds"`
}

// Validate validates this season rounds
func (m *SeasonRounds) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRounds(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SeasonRounds) validateName(formats strfmt.Registry) error {

	if err := m.Name.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("name")
		}
		return err
	}

	return nil
}

func (m *SeasonRounds) validateRounds(formats strfmt.Registry) error {

	if err := validate.Required("rounds", "body", m.Rounds); err != nil {
		return err
	}

	for i := 0; i < len(m.Rounds); i++ {
		if swag.IsZero(m.Rounds[i]) { // not required
			continue
		}

		if m.Rounds[i] != nil {
			if err := m.Rounds[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("rounds" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *SeasonRounds) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SeasonRounds) UnmarshalBinary(b []byte) error {
	var res SeasonRounds
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
