// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
)

// SeasonName season name
//
// swagger:model SeasonName
type SeasonName string

// Validate validates this season name
func (m SeasonName) Validate(formats strfmt.Registry) error {
	return nil
}
