# This is a basic workflow to help you get started with Actions
name: datasets

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: master
  # At 00:00 UTC on Tuesday.
  schedule:
    - cron: 0 0 * * 2

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  create_pr_update_submodule:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Update submodules
        run:  git submodule update --remote 
          
      - name: Create Pull Request 
        uses: peter-evans/create-pull-request@v2
        with:
            token: ${{ secrets.UPDATESUBMODULE }}
            commit-message: Update Datasets
            title: Update Datasets
            body: |
              - Datasets(submodule) updates
  
              Auto-generated by [create-pull-request][1]
 
              [1]: https://github.com/peter-evans/create-pull-request
            branch: update-datasets
      
      
      
      
    
 
        
    
    
    

    
  
  
